In [1]:
import pandas as pd

In [11]:
df = pd.read_csv("viajes_para_ML_sinhoras.csv")

In [12]:
df

,dir_o,dir_d,Num_viajes,Unnamed: 0,Num_escuelas,Num_hospitales,Num_iglesias,Num_zonas_tipicas
0,Santiago,Buin,3,1,245,16,0.0,0.0
1,La Cisterna,Buin,112,1,245,16,0.0,0.0
2,Pedro Aguirre Cerda,Buin,5,1,245,16,0.0,0.0
3,Padre Hurtado,Buin,29,1,245,16,0.0,0.0
4,Pirque,Buin,141,1,245,16,0.0,0.0
...,...,...,...,...,...,...,...,...
1762,Conchali,Vitacura,97,50,95,19,0.0,0.0
1763,Lampa,Vitacura,38,50,95,19,0.0,0.0
1764,Vitacura,Vitacura,39289,50,95,19,0.0,0.0
1765,San Joaquin,Vitacura,33,50,95,19,0.0,0.0
1766,Lo Prado,Vitacura,35,50,95,19,0.0,0.0

In [14]:
df2 = df.groupby("dir_d").sum()
df2

,Num_viajes,Unnamed: 0,Num_escuelas,Num_hospitales,Num_iglesias,Num_zonas_tipicas
dir_d,,,,,,
Buin,55544,30,7350,480,0.0,0.0
Calera de Tango,22202,80,2800,160,0.0,0.0
Cerrillos,34936,129,7095,344,0.0,0.0
Cerro Navia,50696,156,9555,390,0.0,0.0
Colina,124724,150,10350,450,0.0,0.0
Conchali,46828,222,10915,481,0.0,0.0
Curacavi,37145,196,2800,112,0.0,0.0
El Bosque,58771,336,19320,588,0.0,0.0
El Monte,23723,108,1440,36,0.0,0.0
Estacion Central,77737,430,12685,731,0.0,0.0
Huechuraba,60560,385,4725,385,0.0,0.0
Independencia,23887,444,6845,777,111.0,111.0
Isla de Maipo,24123,208,1360,144,0.0,0.0
La Cisterna,49371,602,13975,301,0.0,0.0
La Florida,142550,600,36800,1400,0.0,0.0
La Granja,49329,656,11070,410,0.0,0.0
La Pintana,38351,748,15400,616,0.0,0.0
La Reina,22017,666,7955,481,0.0,0.0
Lampa,50252,589,8835,248,0.0,0.0
Las Condes,160259,760,11400,1672,76.0,76.0
Lo Barnechea,90985,882,6510,672,0.0,0.0
Lo Espejo,30988,968,8360,440,0.0,0.0
Lo Prado,32127,920,6200,360,0.0,0.0
Macul,45307,984,7995,574,0.0,0.0
Maipu,195194,1125,45225,1530,0.0,0.0
Maria Pinto,8115,208,280,40,0.0,0.0
Melipilla,97881,243,3015,198,0.0,0.0
Nunoa,73999,2040,16000,1000,0.0,0.0
Padre Hurtado,40415,1120,6800,120,0.0,0.0
Paine,56761,377,2535,156,0.0,0.0
Pedro Aguirre Cerda,25089,1290,10750,473,0.0,0.0
Penaflor,50725,1116,10080,360,0.0,0.0
Penalolen,107961,1280,14000,840,0.0,0.0
Pirque,22669,1122,1870,238,0.0,0.0
Providencia,52099,1326,8775,2925,117.0,390.0
Pudahuel,94739,1435,12915,902,0.0,0.0
Puente Alto,202242,1476,39975,1271,0.0,0.0
Quilicura,74974,1628,13200,792,0.0,0.0
Quinta Normal,52339,1520,14000,440,0.0,0.0
Recoleta,55637,1521,13260,429,0.0,0.0
Renca,53809,1560,11700,312,0.0,0.0
San Bernardo,128513,1845,29925,1530,0.0,0.0
San Joaquin,24711,1722,8200,533,0.0,0.0
San Jose de Maipo,21909,1161,1485,135,0.0,0.0
San Miguel,52051,1892,13545,1075,0.0,0.0
San Pedro,6178,90,110,12,0.0,0.0
San Ramon,22028,1840,7600,400,0.0,0.0
Santiago,128918,1974,27510,2142,714.0,798.0
Talagante,41991,1296,6885,324,0.0,0.0
Vitacura,56259,1800,3420,684,0.0,0.0

In [19]:
df2.to_csv("training_dataset1.csv", index = True)