In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("training_dataset3.csv")

In [16]:
dfnew = pd.read_csv("nuevos_datos.csv")

In [17]:
df

,dir_d,Num_viajes,Hora_llegada_1,Hora_llegada_2,Hora_llegada_3,Hora_llegada_4,Hora_llegada_5,Hora_llegada_6,Hora_llegada_7,Hora_llegada_8,...,Hora_llegada_18,Hora_llegada_19,Hora_llegada_20,Hora_llegada_21,Hora_llegada_22,Hora_llegada_23,Num_escuelas,Num_hospitales,Num_iglesias,Num_zonas_tipicas
0,Buin,105,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,245,16,0.0,0.0
1,Buin,402,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,245,16,0.0,0.0
2,Buin,426,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,245,16,0.0,0.0
3,Buin,220,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,245,16,0.0,0.0
4,Buin,179,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,245,16,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,Vitacura,1209,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,95,19,0.0,0.0
1196,Vitacura,1440,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,95,19,0.0,0.0
1197,Vitacura,1701,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,95,19,0.0,0.0
1198,Vitacura,1193,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,95,19,0.0,0.0
1199,Vitacura,681,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,95,19,0.0,0.0

In [18]:
dfnew

,Comuna,Superficie_km2,Poblacion,Conexiones_fijas_intenet,M2_areas_verdes,N_micro_empresas,N_pequenas_empresas,N_medianas_empresas,N_grandes_empresas
0,Alhue,845.0,7536,52,0,249,60,6,2
1,Buin,214.0,111934,21439,325865,4134,1076,110,40
2,Calera de Tango,73.3,29019,2657,0,1051,323,41,14
3,Cerrillos,21.0,89520,19788,632472,2495,769,143,104
4,Cerro Navia,11.0,142304,26354,496196,3328,568,43,10
5,Colina,971.2,185599,32579,1219979,4730,1588,250,159
6,Conchali,10.7,139394,32513,488972,3734,884,152,98
7,Curacavi,693.0,36991,3276,94434,1529,319,42,13
8,El Bosque,14.2,171789,35636,465,4227,830,86,23
9,El Monte,118.0,40620,5635,18000,1082,266,21,12
10,Estacion Central,15.0,214470,52799,868892,4934,1304,203,113
11,Huechuraba,44.8,114453,25439,417975,3643,1389,423,445
12,Independencia,7.0,147655,34980,251341,3268,1088,173,54
13,Isla de Maipo,189.0,40803,3636,53757,1395,348,35,15
14,La Cisterna,10.0,101126,30440,139934,3951,1129,151,41
15,La Florida,70.2,405185,115763,1577484,12330,2626,275,94
16,La Granja,10.0,122028,24179,716679,2953,655,67,14
17,La Pintana,30.6,189454,13844,922757,3716,873,143,37
18,La Reina,23.0,100459,28820,437747,4240,1463,176,70
19,Lampa,452.0,131436,20606,0,4122,1224,286,189
20,Las Condes,99.0,335296,123359,2221657,30890,14481,3570,2985
21,Lo Barnechea,1024.0,126816,27202,1088385,6006,3111,558,289
22,Lo Espejo,7.0,103381,13601,379414,2323,447,53,28
23,Lo Prado,7.0,104405,21364,367186,2465,418,26,6
24,Macul,12.9,136278,41276,538214,3863,1016,222,116
25,Maipu,135.5,584053,158938,3341529,16556,3379,331,151
26,Maria Pinto,393.5,15132,198,147572,650,152,33,12
27,Melipilla,1345.0,143779,19190,0,5842,1463,176,58
28,Nunoa,16.9,255823,98545,1117854,11118,3217,529,164
29,Padre Hurtado,80.8,76219,17607,20693,2343,516,52,18
30,Paine,820.0,84379,6607,153774,2849,853,106,64
31,Pedro Aguirre Cerda,10.0,107409,23271,252734,3113,838,146,39
32,Penaflor,69.0,102667,22192,537835,3114,699,58,25
33,Penalolen,54.0,269296,54046,1401018,6738,1423,131,43
34,Pirque,445.3,31134,1761,57805,1085,305,49,20
35,Providencia,14.3,160043,73198,760184,28756,12171,2495,1246
36,Pudahuel,197.0,256607,61302,1126733,6648,1629,348,300
37,Puente Alto,88.0,655033,153696,2997104,17263,2696,174,50
38,Quilicura,58.0,261993,51909,797461,6279,1872,453,471
39,Quinta Normal,13.0,138904,36837,156471,4763,1588,235,97
40,Recoleta,16.0,193605,39371,810648,7677,2624,556,220
41,Renca,24.0,161959,29817,794,3972,1003,214,147
42,San Bernardo,155.0,339043,69448,1550419,9180,2337,392,259
43,San Joaquin,9.7,103871,23731,486919,3348,1122,171,81
44,San Jose de Maipo,4994.8,18917,873,0,783,169,11,5
45,San Miguel,10.0,136835,55568,0,5371,1710,303,85
46,San Pedro,788.0,12132,411,27324,551,146,15,5
47,San Ramon,7.0,86017,13845,494145,2312,455,35,5
48,Santiago,22.0,517280,171687,2103333,39196,13194,2184,1050
49,Talagante,126.0,82900,15156,326793,2917,674,70,25
50,Til Til,653.0,21783,2209,5000,756,227,27,10
51,Vitacura,28.3,97695,34864,2021,7872,4201,918,587

In [19]:
dfnew.rename(columns = {'Comuna':'dir_d'}, inplace = True)
dfnew

,dir_d,Superficie_km2,Poblacion,Conexiones_fijas_intenet,M2_areas_verdes,N_micro_empresas,N_pequenas_empresas,N_medianas_empresas,N_grandes_empresas
0,Alhue,845.0,7536,52,0,249,60,6,2
1,Buin,214.0,111934,21439,325865,4134,1076,110,40
2,Calera de Tango,73.3,29019,2657,0,1051,323,41,14
3,Cerrillos,21.0,89520,19788,632472,2495,769,143,104
4,Cerro Navia,11.0,142304,26354,496196,3328,568,43,10
5,Colina,971.2,185599,32579,1219979,4730,1588,250,159
6,Conchali,10.7,139394,32513,488972,3734,884,152,98
7,Curacavi,693.0,36991,3276,94434,1529,319,42,13
8,El Bosque,14.2,171789,35636,465,4227,830,86,23
9,El Monte,118.0,40620,5635,18000,1082,266,21,12
10,Estacion Central,15.0,214470,52799,868892,4934,1304,203,113
11,Huechuraba,44.8,114453,25439,417975,3643,1389,423,445
12,Independencia,7.0,147655,34980,251341,3268,1088,173,54
13,Isla de Maipo,189.0,40803,3636,53757,1395,348,35,15
14,La Cisterna,10.0,101126,30440,139934,3951,1129,151,41
15,La Florida,70.2,405185,115763,1577484,12330,2626,275,94
16,La Granja,10.0,122028,24179,716679,2953,655,67,14
17,La Pintana,30.6,189454,13844,922757,3716,873,143,37
18,La Reina,23.0,100459,28820,437747,4240,1463,176,70
19,Lampa,452.0,131436,20606,0,4122,1224,286,189
20,Las Condes,99.0,335296,123359,2221657,30890,14481,3570,2985
21,Lo Barnechea,1024.0,126816,27202,1088385,6006,3111,558,289
22,Lo Espejo,7.0,103381,13601,379414,2323,447,53,28
23,Lo Prado,7.0,104405,21364,367186,2465,418,26,6
24,Macul,12.9,136278,41276,538214,3863,1016,222,116
25,Maipu,135.5,584053,158938,3341529,16556,3379,331,151
26,Maria Pinto,393.5,15132,198,147572,650,152,33,12
27,Melipilla,1345.0,143779,19190,0,5842,1463,176,58
28,Nunoa,16.9,255823,98545,1117854,11118,3217,529,164
29,Padre Hurtado,80.8,76219,17607,20693,2343,516,52,18
30,Paine,820.0,84379,6607,153774,2849,853,106,64
31,Pedro Aguirre Cerda,10.0,107409,23271,252734,3113,838,146,39
32,Penaflor,69.0,102667,22192,537835,3114,699,58,25
33,Penalolen,54.0,269296,54046,1401018,6738,1423,131,43
34,Pirque,445.3,31134,1761,57805,1085,305,49,20
35,Providencia,14.3,160043,73198,760184,28756,12171,2495,1246
36,Pudahuel,197.0,256607,61302,1126733,6648,1629,348,300
37,Puente Alto,88.0,655033,153696,2997104,17263,2696,174,50
38,Quilicura,58.0,261993,51909,797461,6279,1872,453,471
39,Quinta Normal,13.0,138904,36837,156471,4763,1588,235,97
40,Recoleta,16.0,193605,39371,810648,7677,2624,556,220
41,Renca,24.0,161959,29817,794,3972,1003,214,147
42,San Bernardo,155.0,339043,69448,1550419,9180,2337,392,259
43,San Joaquin,9.7,103871,23731,486919,3348,1122,171,81
44,San Jose de Maipo,4994.8,18917,873,0,783,169,11,5
45,San Miguel,10.0,136835,55568,0,5371,1710,303,85
46,San Pedro,788.0,12132,411,27324,551,146,15,5
47,San Ramon,7.0,86017,13845,494145,2312,455,35,5
48,Santiago,22.0,517280,171687,2103333,39196,13194,2184,1050
49,Talagante,126.0,82900,15156,326793,2917,674,70,25
50,Til Til,653.0,21783,2209,5000,756,227,27,10
51,Vitacura,28.3,97695,34864,2021,7872,4201,918,587

In [20]:
df3 = pd.merge(df,dfnew,on=["dir_d"])

In [21]:
df3

,dir_d,Num_viajes,Hora_llegada_1,Hora_llegada_2,Hora_llegada_3,Hora_llegada_4,Hora_llegada_5,Hora_llegada_6,Hora_llegada_7,Hora_llegada_8,...,Num_iglesias,Num_zonas_tipicas,Superficie_km2,Poblacion,Conexiones_fijas_intenet,M2_areas_verdes,N_micro_empresas,N_pequenas_empresas,N_medianas_empresas,N_grandes_empresas
0,Buin,105,0,0,0,0,0,0,0,0,...,0.0,0.0,214.0,111934,21439,325865,4134,1076,110,40
1,Buin,402,1,0,0,0,0,0,0,0,...,0.0,0.0,214.0,111934,21439,325865,4134,1076,110,40
2,Buin,426,0,1,0,0,0,0,0,0,...,0.0,0.0,214.0,111934,21439,325865,4134,1076,110,40
3,Buin,220,0,0,1,0,0,0,0,0,...,0.0,0.0,214.0,111934,21439,325865,4134,1076,110,40
4,Buin,179,0,0,0,1,0,0,0,0,...,0.0,0.0,214.0,111934,21439,325865,4134,1076,110,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,Vitacura,1209,0,0,0,0,0,0,0,0,...,0.0,0.0,28.3,97695,34864,2021,7872,4201,918,587
1196,Vitacura,1440,0,0,0,0,0,0,0,0,...,0.0,0.0,28.3,97695,34864,2021,7872,4201,918,587
1197,Vitacura,1701,0,0,0,0,0,0,0,0,...,0.0,0.0,28.3,97695,34864,2021,7872,4201,918,587
1198,Vitacura,1193,0,0,0,0,0,0,0,0,...,0.0,0.0,28.3,97695,34864,2021,7872,4201,918,587
1199,Vitacura,681,0,0,0,0,0,0,0,0,...,0.0,0.0,28.3,97695,34864,2021,7872,4201,918,587

In [22]:
df3.to_csv("training_dataset4.csv", index = False)